name: Build and push Docker containers

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*
  create:
    types: [tag]
  schedule:
    - cron: "10 1 * * 0"

env:
  DOCKER_ORG: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAMES: |
    terraform
    terraform-cloud

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ env.IMAGE_NAMES }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_ORG }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ env.DOCKER_ORG }}/${{ env.IMAGE_NAMES[matrix.image] }}:latest
        dockerfile: "${{ env.IMAGE_NAMES[matrix.image] == 'terraform' ? 'Dockerfile' : 'Dockerfile.cloud' }}"
        build-args: |
          BUILD_DATE=${{ format('{0:yyyy-MM-dd}', steps.buildx.outputs.start-time) }}
        platforms: linux/arm64,linux/arm/v7,linux/amd64

    - name: Publish Docker Image
      uses: docker/publish-action@v1
      with:
        tags: ${{ env.DOCKER_ORG }}/${{ env.IMAGE_NAMES[matrix.image] }}:latest
