name: Build and push Docker images

env:
  IMAGE_NAMES: ${{ github.repository_owner }}/terraform,${{ github.repository_owner }}/terraform-cloud
  IMAGE_PLATFORM: linux/amd64,linux/arm64,linux/386,linux/arm/v7

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*
  create:
    types: [tag]
  schedule:
    - cron: "10 1 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - ${{ github.repository_owner }}/terraform
          - ${{ github.repository_owner }}/terraform-cloud

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qemu
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: tagging
      uses: docker/metadata-action@v4
      with:
        image: "${{ env.IMAGE_NAMES[matrix.image] }}"
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=ref,event=tag
          type=schedule
          type=schedule,pattern={{date 'YYYYMMDD'}}

    - name: Login to Docker hub
      if: github.event.name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      if: github.event.name != 'pull_request'
      uses: docker/build-push-action@v3
      with:
        context: .
        file: "${{ env.IMAGE_NAMES[matrix.image] == 'terraform' ? 'Dockerfile' : 'Dockerfile.cloud' }}"
        platforms: ${{ env.IMAGE_PLATFORM }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.tagging.outputs.tags }}
        labels: ${{ steps.tagging.outputs.labels }}
