name: Build and push Docker images

env:
  IMAGE_PLATFORM: linux/amd64,linux/arm64,linux/386,linux/arm/v7
  IMAGE_FILES: Dockerfile,Dockerfile.cloud

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
    tags:
      - v*
  create:
    types: [tag]
  schedule:
    - cron: "10 1 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - ${{ github.repository_owner }}/terraform
          - ${{ github.repository_owner }}/terraform-cloud

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qemu
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: tagging
      uses: docker/metadata-action@v4
      with:
        images: "${{ matrix.image }}"
        tags: |
          type=raw,pattern=v${{ env.TAG_VERSION }}-{{ env.BRANCH_TAG_SUFFIX }},value={{ env.BRANCH_TAG }},enable=${{ env.TAG_ENABLED }}
          type=raw,value={{ env.BRANCH_TAG }},enable=${{ env.BRANCH_TAG_ENABLED }}
          type=tag,value={{ env.TAG_NAME }},enable=${{ env.TAG_ENABLED }}
          type=sha
          type=date,pattern=v${{ env.TAG_VERSION }}-{{ env.DATE_TAG_SUFFIX }}-{{ env.DATE }},value={{ env.DATE_TAG }},enable=${{ env.DATE_TAG_ENABLED }}

    - name: Login to Docker hub
      if: github.event.name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      if: github.event.name != 'pull_request'
      uses: docker/build-push-action@v3
      with:
        context: .
        file: "${{ env.IMAGE_FILES[job.index] }}"
        platforms: ${{ env.IMAGE_PLATFORM }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.tagging.outputs.tags }}
        labels: ${{ steps.tagging.outputs.labels }}
