name: Build and push Docker image

env:
  IMAGE_NAME: "${{ github.owner }}/terraform"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*
  create:
    types: [tag]
  schedule:
    - cron: "10 1 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qemu
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: tagging
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=ref,event=tag
          type=schedule
          type=schedule,pattern={{date 'YYYYMMDD'}}

    - name: Login to Docker hub
      if: github.event.name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      if: github.event.name != 'pull_request'
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.tagging.outputs.tags }}
        labels: ${{ steps.tagging.outputs.labels }}
