name: Docker build and push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*
  create:
    types: [tag]
  schedule:
    - cron: "10 1 * * 0"

env:
  IMAGE_NAMES:
    terraform: Dockerfile
    terraform-cloud: Dockerfile.cloud

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: [terraform, terraform-cloud]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the Docker image
      id: build-image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          ${{ env.IMAGE_NAME }}:${{ env.TAG }}
        build-arg: |
          FILE=${env.IMAGE_NAMES[matrix.image]}
        push: ${{ env.PUSH }}

    - name: Get the Docker image digest
      id: get-digest
      uses: docker/metadata-action@v4
      with:
        image: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
      env:
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        TAG: ${{ env.TAG }}

    - name: Tag the Docker image
      id: tag-image
      uses: docker/tag-action@v1
      with:
        source: ${{ steps.get-digest.outputs.digest }}
        target: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
      env:
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        TAG: ${{ env.TAG }}
